# Generated by Django 3.1.2 on 2020-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_lastname', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('mob_no', models.CharField(default='', max_length=50)),
                ('email_address', models.IntegerField(default=0)),
            ],
        ),
    ]
