# Generated by Django 3.1.2 on 2020-10-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pr_name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=models.CharField(default='', max_length=70),
        ),
    ]
