# Generated by Django 3.1.2 on 2020-10-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0002_auto_20201024_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
