# Generated by Django 3.1.2 on 2020-10-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0003_person_desc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='pr_name',
        ),
    ]
