# Generated by Django 3.1.2 on 2020-10-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0004_auto_20201025_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='desc',
        ),
        migrations.AddField(
            model_name='person',
            name='conform_password',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='', max_length=70),
        ),
    ]
