# Generated by Django 3.1.2 on 2020-10-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0005_auto_20201026_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='conform_password',
            new_name='confirm_password',
        ),
    ]
