# Generated by Django 3.1.2 on 2020-10-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0006_auto_20201026_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email_address',
            new_name='email',
        ),
    ]
