# Generated by Django 3.1.2 on 2020-10-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0007_auto_20201027_1746'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='email',
        ),
    ]
