# Generated by Django 3.1.2 on 2020-10-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0008_auto_20201027_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterModelTable(
            name='person',
            table='username',
        ),
    ]
