# Generated by Django 3.1.2 on 2020-10-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0009_auto_20201028_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'web_member',
            },
        ),
    ]
