# Generated by Django 3.1.2 on 2020-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0010_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='business_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='confirm_password',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='facebook_id',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram_id',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='mob_no',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter_id',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=70),
        ),
    ]
