# Generated by Django 3.1.2 on 2020-10-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0012_auto_20201028_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
    ]
