# Generated by Django 3.1.2 on 2020-10-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0013_remove_member_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=70),
        ),
    ]
