# Generated by Django 3.1.2 on 2020-10-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0015_member_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='email_id',
        ),
    ]
