# Generated by Django 3.1.2 on 2020-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0017_auto_20201028_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='business_logo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
