# Generated by Django 3.1.2 on 2020-10-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0018_auto_20201028_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='business_logo',
        ),
    ]
