# Generated by Django 3.1.2 on 2020-10-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0019_remove_member_business_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='business_name',
            new_name='b_name',
        ),
    ]
