# Generated by Django 3.1.2 on 2020-10-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0020_auto_20201028_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
