# Generated by Django 3.1.2 on 2020-10-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0021_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='b_name',
            new_name='bname',
        ),
    ]
