# Generated by Django 3.1.2 on 2020-10-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0022_auto_20201029_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bname',
        ),
    ]
