# Generated by Django 3.1.2 on 2020-10-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0023_remove_member_bname'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Business_name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
