# Generated by Django 3.1.2 on 2020-10-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0024_member_business_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Business_name',
            new_name='business_name',
        ),
    ]
