# Generated by Django 3.1.2 on 2020-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0025_auto_20201029_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='twitter_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='website',
        ),
        migrations.RemoveField(
            model_name='member',
            name='whatsapp_number',
        ),
    ]
