# Generated by Django 3.1.2 on 2020-10-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0026_auto_20201029_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='confirm_password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='email_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='mob_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
