# Generated by Django 3.1.2 on 2020-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0027_auto_20201029_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mob', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('c_password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
