# Generated by Django 3.1.2 on 2020-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0028_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mob',
            field=models.IntegerField(),
        ),
    ]
