# Generated by Django 3.1.2 on 2020-10-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0029_auto_20201029_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='Card_App/images')),
            ],
            options={
                'db_table': 'name',
            },
        ),
    ]
