# Generated by Django 3.1.2 on 2020-11-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0032_auto_20201031_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelTable(
            name='design',
            table='product',
        ),
    ]
